// <auto-generated />
namespace OnlineBankingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateapplicationuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateapplicationuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011353510_update-applicationuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
