// <auto-generated />
namespace OnlineBankingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031347178_add-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
